doctrine:
  orm:
    entity_managers:
      default:
        metadata_cache_driver:
          type: 'service'
          id: doctrine.cache.memcached
        query_cache_driver:
          type: 'service'
          id: doctrine.cache.memcached
        result_cache_driver:
          type: 'service'
          id: doctrine.cache.memcached
