#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /guest/book
  controller: App\Controller\GuestBookController::index

save:
  path: /guest/book/save
  controller: App\Controller\GuestBookController::save
